name: 'delete-release-by-tag'

description: 'An action that can be used to delete a GitHub Release by tag.'

inputs:
  github-token:
    description: 'A GitHub token with permission to delete releases.  Generally secrets.GITHUB_TOKEN.'
    required: true
  release-tag:
    description: 'The tag of the release to delete'
    required: true

runs:
  using: 'node12'
  main: 'dist/index.js'
